// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTrBJiqOgfquZs49J0eX1yASfP2eiA5M8',
    appId: '1:127340460080:web:72a462fb2f470147c795f5',
    messagingSenderId: '127340460080',
    projectId: 'signin-a0107',
    authDomain: 'signin-a0107.firebaseapp.com',
    storageBucket: 'signin-a0107.appspot.com',
    measurementId: 'G-MXVYF0EHCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqk_cYrtlJxu8aLb2C_Tv8LL-Sq8RO_sg',
    appId: '1:127340460080:android:9c6d7d12b4fb6b4bc795f5',
    messagingSenderId: '127340460080',
    projectId: 'signin-a0107',
    storageBucket: 'signin-a0107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9BCXleLVYQWRnQPwcOPkFqw0rek9E2Qo',
    appId: '1:127340460080:ios:cad38888136a43b1c795f5',
    messagingSenderId: '127340460080',
    projectId: 'signin-a0107',
    storageBucket: 'signin-a0107.appspot.com',
    androidClientId: '127340460080-mqmropcm87j42ghf6p7v3j52b893k7t9.apps.googleusercontent.com',
    iosClientId: '127340460080-e749dj9ium7e26hm3ep2hu36br2217bg.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9BCXleLVYQWRnQPwcOPkFqw0rek9E2Qo',
    appId: '1:127340460080:ios:f2cfb849655d7a53c795f5',
    messagingSenderId: '127340460080',
    projectId: 'signin-a0107',
    storageBucket: 'signin-a0107.appspot.com',
    androidClientId: '127340460080-mqmropcm87j42ghf6p7v3j52b893k7t9.apps.googleusercontent.com',
    iosClientId: '127340460080-th8641pivebnieaobfdfebcm03upukqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSignin.RunnerTests',
  );
}
